name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic syntax check
        run: python -m py_compile run.py

      - name: Run pytest (si tienes tests)
        run: |
          if [ -d "tests" ]; then
            pip install pytest
            pytest
          else
            echo "No tests directory found, skipping pytest"
