name: Deploy QA – auth-service

on:
  push:
    branches: [ qa ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 using DockerHub image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
            docker stop auth-service || true
            docker rm auth-service || true
            docker run -d --restart always --name auth-service -p 6000:6000 --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

